# Generated by Django 2.2.4 on 2020-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_title',
            field=models.CharField(max_length=30),
        ),
    ]
